name: å¤šç³»ç»ŸåŸç”Ÿæ‰§è¡Œæ–‡ä»¶å‘å¸ƒ
run-name: ${{ github.actor }} GitHub Actions ğŸš€
on:
  push:
    branches:
      - main
    # tags: [ 'v*.*.*' ]  # å¦‚ v1.0.0 ä¼šè§¦å‘æ„å»º
  workflow_dispatch:
jobs:
  build-native:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # platform: [linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64]
        platform: [linux/amd64, linux/arm64]
    name: Build native image for ${{ matrix.platform }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build native image in Docker (musl)
        run: |
          docker run --rm --platform=${{ matrix.platform }} \
            -v $PWD:/app \
            -w /app \
            ghcr.io/graalvm/native-image-community:24-muslib \
            ./mvnw -DskipTests -Pnative native:compile
      - name: View Build target
        run: |
          ls -alh target/
          mkdir -p dist
          cp target/download-proxy dist/download-proxy
      - name: Compress binary with UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            dist/download-proxy
          # args: -fq
          args: --best --lzma
      - name: View UPX target
        run: |
          ls -alh dist/
      - name: Rename binary
        run: |
          PLATFORM_TAG="${{ matrix.platform }}"
          PLATFORM_TAG="${PLATFORM_TAG//\//-}"
          mv dist/download-proxy dist/download-proxy-$PLATFORM_TAG
      - name: Upload to GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-app
          path: dist/download-proxy-*